Implement delete operation in BSTree
spbu-coding-2022/trees-7 pull request #11
Opened 2023-04-02 16:18 UTC by ksenmel

Implemented ``delete`` method in Simple BSTree. 
No automatic testing was done.

2023-04-02 20:26 UTC, aartdem requested changes

2023-04-02 20:26 UTC, aartdem commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +     */
Please write documentation in one line like other functions

2023-04-02 20:26 UTC, aartdem commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +    private fun findMinimumNode(node: SimpleNode<T>): SimpleNode<T> {
Maybe findNodeToReplaceWith ? or something like that

2023-04-02 20:26 UTC, aartdem commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +        deleteLeafNode(nodeToReplaceWith)
nodeToReplaceWith can be the node with one child. This case is not considered

2023-04-03 07:23 UTC, therain7 requested changes
Returning `data` in `delete` is incorrect behavior

2023-04-03 07:23 UTC, therain7 commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +    private fun searchNodeForDelete(data: T): SimpleNode<T>? = searchNode(data)
What's the point of the function? It's the same as `searchNode`

2023-04-03 07:23 UTC, therain7 commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +        if (nodeToDelete == null) return null
```suggestion
        val nodeToDelete = searchNode(data) ?: return null
```

2023-04-03 07:23 UTC, therain7 commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +                else -> deleteNodeWithTwoChildren(nodeToDelete)
```suggestion
                nodeToDelete.left == null && nodeToDelete.right == null ->
                    deleteLeafNode(nodeToDelete)
                    
                nodeToDelete.left == null || nodeToDelete.right == null ->
                    deleteNodeWithOneChild(nodeToDelete)
                    
                else -> deleteNodeWithTwoChildren(nodeToDelete)
```

2023-04-03 07:23 UTC, therain7 commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +        var nodeToDelete = node
The variable is useless here

2023-04-03 07:23 UTC, therain7 commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +        nodeToDelete = nodeToReplaceWith
This assignment doesn't do anything

2023-04-03 07:23 UTC, therain7 commented on lib/src/main/kotlin/bstrees/SimpleBST.kt
> +        val nodeToReplaceWith = findNodeToReplaceWith(node.left!!)
I suggest you edit the function to accept the node to find replacement for.
```suggestion
        val nodeToReplaceWith = findNodeToReplaceWith(node)
```

2023-04-03 14:18 UTC, aartdem approved these changes

2023-04-03 16:13 UTC, therain7 approved these changes

2023-04-03 16:14 UTC, merged